name: FirstGHAction
on: 
  push:
   branches: 
     - main
     - test
jobs:
  TestJob:
    runs-on: ubuntu-latest
    steps:
    - name: First-Step
      run: echo "This is my second GitHub action." 
    - name: LoadRepo
      uses: actions/checkout@v6.0.3
    - name: listRepoFiles
      run: ls -la
  
